```{r {{id}}-set}
if (interactive()) {
  resultaten %>%
    filter(!composite) %>%
    sample_n(1) %>%
    pull(fingerprint) -> id
} else {
  id <- "{{id}}"
}
```

```{r {{id}}-basis}
resultaten %>%
  filter(fingerprint == id) -> deze_index
soort_naam <- deze_index$species_group[1]
```

\pagebreak

## `r soort_naam`

### Indices

```{r {{id}}-vlaanderen-cyclus-data}
deze_index %>%
  filter(
    stratum == "Vlaanderen", cycle, nonlinear, 
    str_detect(parameter, "[0-9]+-[0-9]+")
  ) %>%
  transmute(
    cyclus = factor(parameter),
    index = exp(median), 
    se = ucl - mean,
    analysis, status, stratum
  ) -> aantal_vlaanderen_cyclus
deze_index %>%
  filter(cycle, parameter != "Trend", stratum == "Vlaanderen") %>%
  distinct(nonlinear, waic) -> waic_cyclus
if (nrow(waic_cyclus) > 1) {
  waic_cyclus %>%
    arrange(waic) %>%
    summarise(
      type = nonlinear[1],
      delta = diff(waic)
    ) -> waic_cyclus
  if (waic_cyclus$type) {
    if (waic_cyclus$delta > 5) {
      cap_vlaanderen_cyclus <- "niet lineair"
    } else {
      cap_vlaanderen_cyclus <- "mogelijk niet lineair"
    }
  } else {
    cap_vlaanderen_cyclus <- "lineair"
  }
} else {
  cap_vlaanderen_cyclus <- "onbekend"
}
```

```{r {{id}}-vlaanderen-cyclus, fig.cap = paste0("Gemiddeld aantal waargenomen dieren per punt voor ", soort_naam, " op basis van data geaggregeerd per driejaarlijkse cyclus. De trend is ", cap_vlaanderen_cyclus, "."), fig.height = 50 / 25.4}
if (nrow(aantal_vlaanderen_cyclus)) {
aantal_vlaanderen_cyclus %>%
  ggplot(
    aes(x = cyclus, y = index, link_sd = se, group = analysis)
  ) +
  stat_fan(link = "log") +
  geom_line() +
  scale_y_continuous(
    "Gemiddeld aantal\nwaargenomen\ndieren per meetpunt",
    limits = c(0, NA)
  ) +
  coord_cartesian(
    ylim = c(
      0, 
      max(
        exp(
          qnorm(
            0.95, 
            log(aantal_vlaanderen_cyclus$index), 
            pmin(
              aantal_vlaanderen_cyclus$se,
              4.1
            )
          )
        )
      )
    )
  ) +
  theme(
    axis.title.x = element_blank()
  )
}
```

```{r {{id}}-vlaanderen-jaar-data}
deze_index %>%
  filter(
    stratum == "Vlaanderen", nonlinear, !cycle, 
    str_detect(parameter, "^[0-9]{4}$")
  ) %>%
  transmute(
    jaar = as.integer(parameter),
    index = exp(median), 
    se = ucl - mean,
    analysis, status
  ) -> aantal_vlaanderen_jaar
deze_index %>%
  filter(stratum == "Vlaanderen", !cycle, parameter != "Trend") %>%
  distinct(nonlinear, waic) -> waic_jaar
if (nrow(waic_jaar) == 2) {
  waic_jaar %>%
    arrange(waic) %>%
    summarise(
      type = nonlinear[1],
      delta = diff(waic)
    ) -> waic_jaar
  if (!waic_jaar$type) {
    cap_vlaanderen_jaar <- "lineair"
  } else if (waic_jaar$delta > 5) {
    cap_vlaanderen_jaar <- "niet lineair"
  } else {
    cap_vlaanderen_jaar <- "mogelijk niet lineair"
  }
} else {
  cap_vlaanderen_jaar <- "onbekend"
}
```

```{r {{id}}-vlaanderen-jaar, fig.cap = paste0("Gemiddelde aantal waargenomen dieren per punt voor ", soort_naam, " op basis van jaarlijkse data. De trend is ", cap_vlaanderen_jaar, "."), fig.height = 50 / 25.4}
if (nrow(aantal_vlaanderen_jaar)) {
ggplot(
  aantal_vlaanderen_jaar, 
  aes(x = jaar, y = index, link_sd = se, group = analysis)
) +
  stat_fan(link = "log") +
  geom_line() +
  scale_y_continuous(
    "Gemiddeld aantal\nwaargenomen\ndieren per meetpunt",
    limits = c(0, NA)
  ) +
  coord_cartesian(
    ylim = c(
      0, 
      max(
        exp(
          qnorm(
            0.95, 
            log(aantal_vlaanderen_jaar$index), 
            pmin(
              aantal_vlaanderen_jaar$se,
              4.1
            )
          )
        )
      )
    )
  ) +
  theme(
    axis.title.x = element_blank()
  )
}
```

```{r {{id}}-vlaanderen-cyclus-data-index}
deze_index %>%
  filter(
    stratum == "Vlaanderen", cycle, nonlinear, 
    str_detect(parameter, "[0-9]+ - [0-9]+")
  ) %>%
  extract(
    parameter, 
    into = c("naar", "referentie"), 
    regex = "([0-9]+) - ([0-9]+)", 
    convert = TRUE
  ) %>%
  transmute(
    naar, referentie, median, 
    sigma = (ucl - lcl) / (2 * qnorm(0.975)),
    lcl = qnorm(0.05, mean, sigma),
    ucl = qnorm(0.95, mean, sigma)
  ) -> index_cyclus
index_cyclus %>%
  rename(
    referentie = naar,
    naar = referentie,
    lcl = ucl, 
    ucl = lcl
  ) %>%
  mutate_at(c("median", "lcl", "ucl"), function(x){-x}) %>%
  bind_rows(index_cyclus) -> index_cyclus
```

```{r {{id}}-vlaanderen-cyclus-index-eerste, fig.cap = paste0("Wijziging t.o.v. de eerste cyclus voor ", soort_naam, " op basis van driejaarlijkse data."), fig.height = 50 / 25.4}
if (nrow(index_cyclus)) {
  index_cyclus %>%
    filter(referentie == min(referentie)) %>%
    mutate(naar = sprintf("%i-%i", naar, naar + 2)) %>%
    ggplot(aes(x = naar, y = median, ymin = lcl, ymax = ucl, link_sd = sigma)) + 
    geom_hline(yintercept = c(0, 1, -1) * log(0.75), linetype = c(2, 3, 3)) +
    stat_fan(geom = "rect") +
    stat_effect(threshold = log(0.75)) +
    scale_y_continuous(
      "procentuele wijziging\nt.o.v. eerste cyclus",
      breaks = index_breaks,
      labels = index_labels,
      sec.axis = sec_axis(
        trans = exp,
        breaks = function(x) {
          exp(index_breaks(log(x)))
        },
        labels = function(x) {
          signif(x, 3)
        },
        name = "relatieve wijziging\nt.o.v. eerste cyclus"
      )
    ) +
    scale_effect("klasse") +
    theme(
      axis.title.x = element_blank()
    )
}
```

```{r {{id}}-vlaanderen-jaar-data-index}
deze_index %>%
  filter(
    stratum == "Vlaanderen", !cycle, nonlinear, 
    str_detect(parameter, "[0-9]+ - [0-9]+")
  ) %>%
  extract(
    parameter, 
    into = c("naar", "referentie"), 
    regex = "([0-9]+) - ([0-9]+)", 
    convert = TRUE
  ) %>%
  transmute(
    naar, referentie, median, 
    sigma = (ucl - lcl) / (2 * qnorm(0.975)),
    lcl = qnorm(0.05, mean, sigma),
    ucl = qnorm(0.95, mean, sigma)
  ) -> index_jaar
index_jaar %>%
  rename(
    referentie = naar,
    naar = referentie,
    lcl = ucl, 
    ucl = lcl
  ) %>%
  mutate_at(c("median", "lcl", "ucl"), function(x){-x}) %>%
  bind_rows(index_jaar) -> index_jaar
```

```{r {{id}}-vlaanderen-jaar-index-eerste, fig.cap = paste0("Wijziging t.o.v. de eerste jaar voor ", soort_naam, " op basis van jaarlijkse data."), fig.height = 50 / 25.4}
if (nrow(index_jaar)) {
  index_jaar %>%
    filter(referentie == min(referentie)) %>%
    ggplot(aes(x = naar, y = median, ymin = lcl, ymax = ucl, link_sd = sigma)) + 
    geom_hline(yintercept = c(0, 1, -1) * log(0.75), linetype = c(2, 3, 3)) +
    stat_fan(geom = "rect") +
    stat_effect(threshold = log(0.75)) +
    scale_x_continuous(breaks = pretty) +
    scale_y_continuous(
      "procentuele wijziging\nt.o.v. eerste jaar",
      breaks = index_breaks,
      labels = index_labels,
      sec.axis = sec_axis(
        trans = exp,
        breaks = function(x) {
          exp(index_breaks(log(x)))
        },
        labels = function(x) {
          signif(x, 3)
        },
        name = "relatieve wijziging\nt.o.v. eerste jaar"
      )
    ) +
    scale_effect("klasse") +
    theme(
      axis.title.x = element_blank()
    )
}
```

```{r {{id}}-vlaanderen-jaar-cyclus-alles, fig.cap = paste0("Paarsgewijze vergelijking tussen cycli voor ", soort_naam, " op basis van driejaarlijkse data."), fig.width = 120 / 25.4, fig.height = 90 / 25.4}
if (nrow(index_cyclus)) {
  ggplot(
    index_cyclus,
    aes(x = naar, y = referentie, ymin = lcl, ymax = ucl, colour = median)
  ) +
    stat_effect(threshold = log(0.75)) +
    scale_effect("klasse") +
    scale_x_continuous(
      breaks = function(x) {
        seq(x[1] + 0.5, x[2], by = 3)
      },
      labels = function(x) {
        sprintf("%i - %i", x, x + 2)
      },
      expand = c(0, 0.5)
    ) +
    scale_y_continuous(
      breaks = function(x) {
        seq(x[1] + 0.5, x[2], by = 3)
      },
      labels = function(x) {
        sprintf("%i - %i", x, x + 2)
      },
      expand = c(0, 0.5)
    ) +
    scale_colour_gradient2(
      "procentuele\nwijziging",
      breaks = index_breaks,
      labels = index_labels
    ) +
    coord_fixed() +
    theme(
      axis.title.x = element_blank(),
      axis.text.x = element_text(angle = 90)
    )
}
```

```{r {{id}}-vlaanderen-jaar-index-alles, fig.cap = paste0("Paarsgewijze vergelijking tussen jaren voor ", soort_naam, " op basis van jaarlijkse data."), fig.height = 90 / 25.4}
if (nrow(index_jaar)) {
  ggplot(
    index_jaar,
    aes(x = naar, y = referentie, ymin = lcl, ymax = ucl, colour = median)
  ) +
    stat_effect(threshold = log(0.75)) +
    scale_effect("klasse") +
    scale_x_continuous(breaks = pretty) +
    scale_y_continuous(breaks = pretty) +
    scale_colour_gradient2(
      "procentuele\nwijziging",
      breaks = index_breaks,
      labels = index_labels
    ) +
    coord_fixed() +
    theme(axis.title.x = element_blank())
}
```


### Overzicht gebruikte waarnemingen

```{r {{id}}-get-design}
deze_index %>%
  filter(!cycle, !nonlinear) %>%
  distinct(analysis) %>%
  pull(analysis) -> fp
if (length(fp)) {
  design <- raw_results[[fp]]$design
} else {
  design <- NULL
}
```

```{r {{id}}-totaal, results = "asis", eval = !is.null(design)}
if (has_name(design$total, "stratum")) {
  strata_description %>%
    rename(stratum = description) %>%
    inner_join(
      design$total %>%
        mutate(stratum = as.character(stratum)), 
      by = c("fingerprint" = "stratum")
    ) %>%
    select(stratum, hokken = n_location, bezoeken = n_visit) -> effort
} else {
  design$total %>%
    select(hokken = n_location, bezoeken = n_visit) -> effort
}
effort %>%
  arrange(desc(hokken), desc(bezoeken)) %>%
  kable(caption = paste("Totale monitoringinspanning voor", soort_naam))
```

```{r {{id}}-herbezoek, eval = !is.null(design)}
design$revisit %>%
  arrange(visits) %>%
  select("aantal jaren bezocht" = visits, "aantal hokken" = n) %>%
  kable(caption = paste("Graad van herbezoek voor", soort_naam))
```

```{r {{id}}-zoekinspanning-stratum, fig.cap = paste("Evolutie van het aantal onderzochte hokken voor", soort_naam), eval = !is.null(design)}
if (has_name(design$total, "stratum")) {
  strata_description %>%
    rename(stratum = description) %>%
    inner_join(
      design$time_obs %>%
        ungroup() %>%
        mutate(stratum = as.character(stratum)), 
      by = c("fingerprint" = "stratum")
    ) %>%
    transmute(
      stratum, jaar = cyear + 2006, 
      hokken = n_location, mean_obs, min_obs, max_obs
    ) -> inspanning_stratum
  kleuren <- sort(strata_description$description)
  kleuren <- inbo.2015.colours(length(kleuren)) %>%
    setNames(kleuren)
  ggplot(inspanning_stratum, aes(x = jaar, y = hokken, colour = stratum)) +
    geom_line() +
    ylim(0, NA) +
    scale_colour_manual(values = kleuren) +
    ylab("aantal onderzochte hokken") +
    theme(axis.title.x = element_blank())
} else {
  design$time_obs %>%
    transmute(
      jaar = cyear + 2006, 
      hokken = n_location, mean_obs, min_obs, max_obs
    ) -> inspanning_stratum
  ggplot(inspanning_stratum, aes(x = jaar, y = hokken)) +
    geom_line() +
    ylim(0, NA) +
    ylab("aantal onderzochte hokken") +
    theme(axis.title.x = element_blank())
}
```

```{r {{id}}-zoekinspanning-hok, fig.cap = paste0("Aantal waarnemingen per hok en per jaar voor ", soort_naam, ". De lijn geeft het gemiddelde, de band het minimum en het maximum."), eval = !is.null(design)}
p <- ggplot(
  inspanning_stratum, 
  aes(x = jaar, y = mean_obs, ymin = min_obs, ymax = max_obs)
) +
  geom_ribbon(alpha = 0.2) +
  geom_line() +
  scale_y_continuous("Aantal waarnemingen per hok en per jaar") +
  coord_cartesian(ylim = c(0, 18))
if (has_name(inspanning_stratum, "stratum")) {
  p + facet_wrap(~stratum)
} else {
  p
}
```

```{r {{id}}-totale-inspanning, fig.cap = paste("Evolutie van de totale zoekinspanning voor ", soort_naam), eval = !is.null(design)}
design[[4]] %>%
  transmute(
    jaar = time + 2006, onderzocht = n, nieuw = new, cummulatief = cumsum(new)
  ) %>%
  gather("kenmerk", "hokken", -jaar) %>%
  mutate(
    kenmerk = factor(kenmerk, levels = c("cummulatief", "onderzocht", "nieuw"))
  ) %>%
  ggplot(aes(x = jaar, y = hokken, colour = kenmerk, linetype = kenmerk)) +
  geom_line() +
  ylab("aantal hokken")
```

```{r {{id}}-tussentijd, fig.cap = paste0("Aantal jaren sinds het vorige bezoek aan een hok voor ", soort_naam, ". De lijn geeft het gemiddelde weer. De band geeft het minimum en het maximum weer."), eval = !is.null(design)}
design[[4]] %>%
  filter(time > 1) %>%
  transmute(
    jaar = time + 2006, min_delta, max_delta, mean_delta
  ) %>%
  ggplot(aes(x = jaar, y = mean_delta, ymin = min_delta, ymax = max_delta)) +
  geom_ribbon(alpha = 0.2) +
  geom_line() +
  scale_y_continuous("Jaren sinds vorig bezoek", limits = c(1, NA))
```

\clearpage

### Trends per stratum

```{r {{id}}-stratum-lineair, results = "asis"}
deze_index %>%
  filter(parameter == "Trend", !nonlinear) %>%
  mutate(
    median = 100 * exp(median * ifelse(cycle, 5, 15)) - 100,
    lcl = 100 * exp(lcl * ifelse(cycle, 5, 15)) - 100,
    ucl = 100 * exp(ucl * ifelse(cycle, 5, 15)) - 100,
    cycle = ifelse(cycle, "driejaarlijks", "jaarlijks")
  ) %>%
  left_join(strata_description, by = c("stratum" = "fingerprint")) %>%
  transmute(
    stratum = ifelse(is.na(description), stratum, description),
    stratum = reorder(
      stratum, 
      ifelse(
        stratum == "Vlaanderen", 
        Inf, 
        ifelse(cycle == "driejaarlijks", median, 0)
      )
    ),
    cycle,
    trend = sprintf(
      "%s%0.1f%% (%0.1f%%; %0.1f%%)%1$s", 
      ifelse(ucl < 0 | lcl > 0, "**", ""), median, lcl, ucl
    )
  ) %>%
  spread(cycle, trend) %>%
  kable(
    caption = paste(
      "Gemiddelde wijziging over 15 jaar voor ", 
      soort_naam, 
      "in de veronderstelling van een lineaire trend."
    ),
    format = "markdown"
  )
```

```{r {{id}}-stratum-nl-cyclus, fig.cap = paste("Niet lineaire trends per stratum voor", soort_naam, "op basis van de data geaggregeerd per driejaarlijkse cyclus.")}
deze_index %>%
  filter(
    !stratum %in% c("Vlaanderen", "distribution", "dispersion"), 
    cycle, 
    parameter != "Trend"
) -> stratum_trend_cyclus
if (nrow(stratum_trend_cyclus)) {
stratum_trend_cyclus %>%
  transmute(
    cyclus = as.integer(parameter) * 3 + 2006,
    cyclus = paste(cyclus, cyclus + 2, sep = "-") %>%
      factor(),
    index = median,
    se = ucl - median,
    nonlinear, analysis, status, stratum
  ) %>%
  ggplot(
    aes(x = cyclus, y = index, link_sd = se, group = stratum)
  ) +
  stat_fan() +
  geom_line() +
  geom_hline(yintercept = 0, linetype = 3) +
  facet_wrap(~stratum, scales = "free_y") +
  scale_y_continuous("log effect") +
  theme(
    axis.title.x = element_blank(),
    axis.text.x = element_text(angle = 90)
  )
}
```

```{r {{id}}-stratum-nl-jaar, fig.cap = paste("Niet lineaire trends per stratum voor", soort_naam, "op basis van jaarlijkse data.")}
deze_index %>%
  filter(
    !stratum %in% c("Vlaanderen", "distribution", "dispersion"), 
    !cycle, 
    parameter != "Trend"
) %>%
  transmute(
    jaar = as.integer(parameter) + 2006,
    index = median, se = ucl - median,
    nonlinear, waic, analysis, status, stratum
  ) -> stratum_trend_jaar
if (nrow(stratum_trend_jaar)) {
  ggplot(stratum_trend_jaar, aes(x = jaar, y = index, link_sd = se)) +
  stat_fan() +
  geom_line() +
  geom_hline(yintercept = 0, linetype = 3) +
  facet_wrap(~stratum, scales = "free_y") +
  scale_y_continuous("log index") +
  theme(
    axis.title.x = element_blank()
  )
}
```

### Modelvalidatie

```{r {{id}}-mv}
deze_index %>%
  distinct(analysis, cycle, nonlinear) %>%
  mutate(
    cycle = ifelse(cycle, "driejaarlijks", "jaarlijks"),
    nonlinear = ifelse(nonlinear, "niet lineair", "log lineair"),
    model = interaction(cycle, nonlinear, sep = "\n"),
    result = raw_results[analysis],
    dispersion = map(result, "dispersion"),
    distribution = map(result, "distribution")
  ) %>%
  select(-result) -> model_validation
```

```{r {{id}}-dispersion, fig.cap = paste("Controleer de dispersie voor", soort_naam)}
model_validation %>%
  transmute(
    model, 
    observed = map_dbl(dispersion, "data"), 
    dispersion = map(dispersion, "model")
  ) %>%
  unnest() %>%
  ggplot(aes(x = dispersion, colour = model)) +
  geom_density() +
  geom_vline(aes(xintercept = observed, colour = model), linetype = 2)
```

```{r {{id}}-distribution, fig.cap = paste("Controleer de distributie voor", soort_naam)}
model_validation %>%
  select(model, distribution) %>%
  unnest() %>%
  mutate(
    median = ecdf / median,
    lcl = ecdf / lcl,
    ucl = ecdf / ucl
  ) %>%
  ggplot(aes(x = x, y = median)) +
  geom_hline(yintercept = 1, linetype = 2) +
  geom_ribbon(aes(fill = model, ymin = lcl, ymax = ucl), alpha = 0.1) +
  geom_line(aes(colour = model)) +
  geom_blank(
    data = data.frame(x = 0, median = c(0.95, 1.05))
  ) + 
  scale_y_continuous("observed / expected ecdf", labels = percent)
```

### Fingerprints

soortgroep: `{{id}}`

```{r {{id}}-fingerprint, results = "asis"}
deze_index %>%
  distinct(model_type, analysis, status, cycle, nonlinear) %>%
  arrange(cycle, nonlinear) %>%
  transmute(
    output = sprintf(
      "- %s\n    - analysis: `%s`\n    - status: `%s`", 
      model_type, analysis, status
    )
  ) %>%
  pull(output) %>%
  cat(sep = "\n")
```
