```{r {{id}}-set}
if (interactive()) {
  resultaten$meta %>%
    filter(composite) %>%
    sample_n(1) %>%
    pull(hash) -> id
} else {
  id <- "{{id}}"
}
```

```{r {{id}}-basis}
wijziging %>%
  filter(hash == id) -> deze_wijziging
resultaten$meta %>%
  filter(hash == id) %>%
  slice(1) %>%
  pull(species_group) -> soort_naam
composite_soort %>%
  filter(hash == id) %>%
  arrange(soort) %>%
  pull(soort) -> deze_soorten
deze_threshold <- log(0.75) / sqrt(length(deze_soorten))
```

# `r sprintf("%s {#soort-%s}", soort_naam, id)`

Deze indicator is gebaseerd op volgende soorten: `r paste(deze_soorten, collapse = ", ")`.
De indicator bestaat uit `r length(deze_soorten)` soorten.
De aangepaste grenswaarden zijn `r sprintf("%+.1f%%", exp(deze_threshold) * 100 - 100)` en `r sprintf("%+.1f%%", exp(-deze_threshold) * 100 - 100)`.


```{r {{id}}-wijziging-jaar, fig.cap = "Wijzigingen t.o.v. het eerste jaar.", eval = nrow(deze_wijziging) > 0}
deze_wijziging %>%
  filter(referentie == min(referentie)) %>%
  ggplot(aes(x = naar, y = log_mean, link_sd = log_sd)) +
  geom_hline(yintercept = 0, linetype = 2) +
  geom_hline(yintercept = c(-1, 1) * deze_threshold, linetype = 3) +
  stat_fan(geom = "rect") +
  stat_effect(
    aes(
      ymin = qnorm(0.05, log_mean, log_sd), 
      ymax = qnorm(0.95, log_mean, log_sd)
    ), 
    threshold = deze_threshold
  ) +
  scale_effect("klasse") +
  scale_x_continuous(breaks = pretty) +
  scale_y_continuous(
    "procentuele wijziging t.o.v. 2007", 
    breaks = index_breaks, labels = index_labels,
    sec.axis = sec_axis(
      trans = exp, name = "relatieve wijziging t.o.v. 2007",
      breaks = function(x){exp(index_breaks(log(x)))}, 
      labels = function(x){signif(x, 3)}
    )
  ) +
  theme(axis.title.x = element_blank())
```

```{r {{id}}-wijziging-jaar-alles, fig.cap = paste0("Paarsgewijze vergelijking tussen jaren voor ", soort_naam, "."), eval = nrow(deze_wijziging) > 0}
deze_wijziging %>%
  mutate(
    lcl = qnorm(0.05, log_mean, log_sd),
    ucl = qnorm(0.95, log_mean, log_sd),
    klasse = classification(lcl, ucl, deze_threshold),
    wijziging = sprintf(
      "%i: %s t.o.v. %i (%s)", 
      naar,
      display_trend(log_mean, lcl, ucl),
      referentie,
      klasse
    ),
    klasse = remove_sign(klasse)
  ) -> change
tickvals <- index_breaks2(change$log_mean)
plot_ly(
  change,
  x = ~naar, y = ~referentie, color = ~log_mean, symbol = ~klasse, 
  text = ~wijziging, hoverinfo = "text"
) %>%
  add_markers(
    colors = c(inbo.steun.blauw, inbo.lichtgrijs, inbo.rood),
    marker = list(
      size = 12
    ),
    symbols = c(
      "triangle-up", "square", "diamond", "circle", "diamond-open", 
      "circle-open"
    )
  ) %>%
  colorbar(
    title = "wijziging", tickvals = tickvals, ticktext = index_labels(tickvals)
  ) %>%
  layout(xaxis = list(title = list(text = NULL)))
```
