---
title: "ABV monitoring: design and analysis"
author: "Thierry Onkelinx"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ABV monitoring: design and analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

ABV stands for Algemene Broedvogelmonitoring Vlaanderen: the common breeding bird census for Flanders (Belgium.)

## Design

- UTM 1x1 km grid cells are stratified based on the landuse.
- Stratified random sample of 1200 grid cells. Rare strata are oversampled, common strata undersampled.
- Every year 300 grid cells are sampled. Grid cells are revisited every 3 year.
- Within each grid cell 6 points on a 3 by 2 grid are predefined.
- Each of the six points is visited during a fixed amount of time and the number of breeding bird are counted.
- The survey is repeated during 3 consective periods of 6 weeks in spring:
    1. from the 1st of March to the 15th of April
    1. from the 16st of April to the 31th of May
    1. from the 1st of June to the 15th of July

## Analysis

### Data selection

- Since not all species are omnipresent, we must select only the relevant locations.
- The same principle is applied to all species.

**Rules:**

- No observations prior to 2007.
- Don't include the latest year until most of the observations are available in the dataset. This is relevant in case the analysis is run during or just after the field campaign.
- No observations outside the 1st of March - 15th of July window.
- No observations which have been marked unreliablein the database.
- Only periods in which the average count is at least 15% of the period with the highest average count.
- Only grid cells in which the species was present in two different years.
- Only strata with at least 3 grid cells with relevant data are used.

### Statistical model

- Generalised linear mixed model with negative binomial distribution.
- Reponse: 
    - Number of observed breeding bird at each point within the grid cell
- Covariates:
    - _Stratum_: takes the average difference in abundance among strata into account.
    - Random walk model of order 1 along _Year_ per _Stratum_. This models a separate non-linear trend for each stratum.
    - _Period_: categorical factor models the overall differences among periods. Only relevant in case multiple periods are selected.
    - _Location_: i.i.d. random intercept of grid cell. This models effects of the grid cell not captured by _Stratum_, _Period_ or _Year_.
    - _SubLocation_: i.i.d. random intercept of point within grid cell. This models effects of the point within the grid cell not captured by _Stratum_, _Period_, _Year_ or _Location_.
- Model fit in [R](http://www.r-project.org) with [INLA](http://www.r-inla.org).

### Trend

- The overall trend is based on a weighted average over the strata.
- The weight $w_i$ of stratum $i$ is based on three variables:
    1. $N_i$: The total number of grid cells of stratum $i$ in Flanders.
    1. $n_i$: The number of sampled grid cells of stratum $i$. This implies $n_i \le N_i$.
    1. $p_i$: The number of sampled grid cells of stratum $i$ in which the species was observed. This implies $p_i \le n_i$.
- $\dfrac{p_i}{n_i}$ is the proportion of sampled grid cells of stratum $i$ in which the species is observed.
- $P_i=N_i\dfrac{p_i}{n_i}$ is the expected number of grid cells of stratum $i$ in which the species is present.
- $w_i = \dfrac{P_i}{\sum{P_i}}$ is $P_i$ scaled by the sum of all $P_i$ so that $\sum{w_i} = 1$.
