project:
  type: website
  output-dir: ../website
  lib-dir: libs

knitr:
  opts_chunk:
    echo: false
    message: false
    warning: false

execute:
  echo: false
  freeze: auto

format:
  inboqmd-report-website-html:
    bibliography: references.bib

flandersqmd:
  title: "Trends op basis van de Algemene Broedvogelmonitoring Vlaanderen (ABV)"
  subtitle: "Technisch achtergrondrapport voor de periode 2007-2023"
  author:
    - name:
        given : Thierry
        family: Onkelinx
      email: thierry.onkelinx@inbo.be
      orcid: 0000-0001-8804-4216
      affiliation: Research Institute for Nature and Forest (INBO)
      corresponding: true
    - name:
        given: Olivier
        family: Dochy
      email: olivier.dochy@inbo.be
      orcid: 0009-0002-2822-5634
      affiliation: Research Institute for Nature and Forest (INBO)
    - name:
        given: Glenn
        family: Vermeersch
      email: glenn.vermeersch@inbo.be
      orcid: 0000-0002-9176-8917
      affiliation: Research Institute for Nature and Forest (INBO)
    - name:
        given: Koen
        family: Devos
      email: koen.devos@inbo.be
      orcid: 0000-0001-7265-6349
      affiliation: Research Institute for Nature and Forest (INBO)
  reviewer:
    - name:
        given: Hans
        family: Van Calster
      email: hans.vancalster@inbo.be
      orcid: 0000-0001-8595-8426
      affiliation: Research Institute for Nature and Forest (INBO)
  lang: nl-BE
  style: INBO
  funder: Research Institute for Nature and Forest (INBO)
  rightsholder: Research Institute for Nature and Forest (INBO)
  community: inbo
  keywords: natuurindicator; trend; broedvogel; citizen science
  publication_type: report
  reportnr: 15
  year: 2024
  doi: 10.21436/inbor.102669823
  depotnr: D/2024/3241/046
  bibliography: references.bib
  link-citations: TRUE
  site: bookdown::bookdown_site
  cooperation:
    - Natuurpunt Studie vzw
    - Coxiestraat 11, 2800 Mechelen
    - https://www.natuurpunt.be
  cooperation_logo: natuurpunt.png
  coverphoto: https://img2.vildaphoto.net/asset/l/86103.jpg
  coverdescription: Putter (_Carduelis carduelis_) eet zaden uit een kaardebol. (© Lars Soerink, Vildaphoto)
  cover: cover.png
  embargo: 2024-03-25
  floatbarrier: section

website:
  title: Algemene Broedvogelmonitoring Vlaanderen (ABV) 2007-2023
  navbar:
    left:
      - text: Cover
        file: index.md
      - text: Samenvatting
        file: samenvatting.md
      - text: Methodologie
        file: methodologie/index.qmd
      - text: Samengestelde indices
        file: index/bos.qmd
      - text: Trends per soort
        file: soort/index.qmd
    tools:
      - icon: mastodon
        href: https://mastodon.online/@inbo
      - icon: twitter
        href: https://twitter.com/inbovlaanderen
      - icon: facebook
        href: https://www.facebook.com/INBOVlaanderen/
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/inbo/abvanalysis
          - text: Report a Bug
            url:  https://github.com/inbo/abvanalysis/issues
  sidebar:
    logo: cover.png
    style: "docked"
    search: false
    contents:
    - text: Cover
      file: index.md
    - samenvatting.md
    - abstract.md
    - section: "Methodologie"
      file: methodologie/index.qmd
      contents:
      - text: "Inzameling van de tellingen in het veld"
        file: methodologie/index.qmd
      - text: "Verwerking van de gegevens"
        file: methodologie/verwerking.qmd
      - text: "Voorstelling van de gegevens"
        file: methodologie/voorstelling.qmd
      - text: "Reproduceerbaarheid en traceerbaarheid van de gegevensverwerking"
        file: methodologie/reproduceerbaarheid.qmd
