project:
  type: website
  output-dir: ../website

knitr:
  opts_chunk:
    echo: false
    message: false
    warning: false

execute:
  echo: false
  freeze: auto

bibliography: references.bib

lang: nl-BE

format:
  flandersqmd-website-html: default

flandersqmd:
  title: "Trends op basis van de Algemene Broedvogelmonitoring Vlaanderen (ABV)"
  subtitle: "Technisch achtergrondrapport voor de periode 2007-2025"
  shorttitle: "abv-trends-2007-2025"
  author:
    - name:
        given: Thierry
        family: Onkelinx
      email: thierry.onkelinx@inbo.be
      orcid: 0000-0001-8804-4216
      affiliation:
        - Instituut voor Natuur- en Bosonderzoek (INBO)
      corresponding: true
    - name:
        given: Olivier
        family: Dochy
      email: olivier.dochy@inbo.be
      orcid: 0009-0002-2822-5634
      affiliation:
        - Instituut voor Natuur- en Bosonderzoek (INBO)
    - name:
        given: Glenn
        family: Vermeersch
      email: glenn.vermeersch@inbo.be
      orcid: 0000-0002-9176-8917
      affiliation:
        - Instituut voor Natuur- en Bosonderzoek (INBO)
    - name:
        given: Koen
        family: Devos
      email: koen.devos@inbo.be
      orcid: 0000-0001-7265-6349
      affiliation:
        - Instituut voor Natuur- en Bosonderzoek (INBO)
  reviewer:
    - name:
        given: Hans
        family: Van Calster
      email: hans.vancalster@inbo.be
      orcid: 0000-0001-8595-8426
      affiliation:
        - Instituut voor Natuur- en Bosonderzoek (INBO)
  entity: INBO
  level: 2
  funder:
    - name:
        given: Instituut voor Natuur- en Bosonderzoek (INBO)
      email: info@inbo.be
      ror: 00j54wy13
  rightsholder:
    - name:
        given: Instituut voor Natuur- en Bosonderzoek (INBO)
      email: info@inbo.be
      ror: 00j54wy13
  publisher: Instituut voor Natuur- en Bosonderzoek (INBO)
  license: CC-BY-4.0
  community: inbo
  keywords: natuurindicator; trend; broedvogel; citizen science
  publication_type: publication-report
  reportnr: 14
  year: 2026
  doi: 10.21436/inbor.141312967
  depotnr: D/2026/3241/066
  bibliography: references.bib
  link-citations: TRUE
  site: bookdown::bookdown_site
  cooperation:
    - Natuurpunt Studie vzw
    - Coxiestraat 11, 2800 Mechelen
  cooperationurl: https://www.natuurpunt.be
  cooperationlogo: natuurpunt.png
  coverphoto: https://img3.vildaphoto.net/asset/l/186414.jpg
  coverdescription: Halsbandparkiet _Psittacula krameri_ zittend op een tak. (© Yves Adams, Vildaphoto)
  embargo: 2026-03-20
  floatbarrier: section
  hyphenation:
    - do-cu-men-teert

website:
  navbar:
    left:
      - text: Cover
        file: index.md
      - text: Samenvatting
        file: samenvatting.md
      - text: Methodologie
        file: methodologie/inzameling.qmd
      - text: Samengestelde indices
        file: index/bos.qmd
      - text: Trends per soort
        file: soort/trends.qmd
    tools:
      - icon: download
        href: onkelinx_etal_2025_abv.pdf
      - icon: mastodon
        href: https://mastodon.online/@inbo
      - icon: facebook
        href: https://www.facebook.com/INBOVlaanderen/
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/inbo/abvanalysis
          - text: Report a Bug
            url:  https://github.com/inbo/abvanalysis/issues
  sidebar:
    logo: cover.png
    style: "docked"
    search: false
    contents:
    - text: Cover
      file: index.md
    - samenvatting.md
    - abstract.md
    - section: "Methodologie"
      contents:
      - text: "Inzameling van de tellingen in het veld"
        file: methodologie/inzameling.qmd
      - text: "Verwerking van de gegevens"
        file: methodologie/verwerking.qmd
      - text: "Voorstelling van de gegevens"
        file: methodologie/voorstelling.qmd
      - text: "Reproduceerbaarheid en traceerbaarheid van de gegevensverwerking"
        file: methodologie/reproduceerbaarheid.qmd
