# Samengestelde indices

Dit hoofdstuk geeft de verschillende samengestelde indices. Elke samengestelde index is het gemiddelde van de set van indices van individuele soorten. We gebruiken hierbij enkel de indices gebaseerd op niet-lineaire trends. We geven telkens de index gebaseerd op jaarlijkse gegevens en na aggregatie per driejarige cyclus. Tot slot geven we nog voor elke index de controlesommen weer voor de analyse en de status. Deze controlesommen laten toe om de reproduceerbaarheid van de verwerking te na te gaan. Aanpassing in de data zullen leiden tot een andere controlesom voor zowel de analyse als de status. Aanpassingen aan de berekeningwijze tussen enkel leiden tot een andere controlesom voor de status.

```{r samengesteld, results='asis', cache = FALSE}
composite %>%
  distinct(fingerprint, species_group) %>%
  arrange(species_group) %>%
  pull(fingerprint) %>%
  sapply(
    function(id) {
      knit_expand("_samengesteld.Rmd", id = id)
    }
  ) %>%
  paste(collapse = "\n\n") -> rmd
knit(text = rmd, quiet = TRUE) %>%
  cat()
```

