```{r {{id}}-basis}
id <- "{{id}}"
species %>%
  filter(fingerprint == id) -> deze_index
soort_naam <- deze_index$species_group[1]
```

## `r soort_naam` {#soort-{{id}}}

```{r {{id}}-vlaanderen-jaar-data}
deze_index %>%
  filter(!cycle, parameter != "Trend") %>%
  transmute(
    jaar = as.integer(parameter),
    index = median, lcl, ucl,
    non_linear, waic, analysis, status
  ) -> index_vlaanderen_jaar
index_vlaanderen_jaar %>%
  group_by(non_linear) %>%
  summarise(referentie = mean(index)) %>%
  inner_join(index_vlaanderen_jaar, by = "non_linear") %>%
  mutate(
    index = exp(index - referentie),
    lcl = exp(lcl - referentie),
    ucl = exp(ucl - referentie)
  ) %>%
  select(-referentie) -> index_vlaanderen_jaar
index_vlaanderen_jaar %>%
  distinct(non_linear, waic) %>%
  arrange(waic) %>%
  summarise(
    type = non_linear[1],
    delta = diff(waic)
  ) -> waic_jaar
if (!waic_jaar$type) {
  cap_vlaanderen_jaar <- "log lineair"
} else if (waic_jaar$delta > 5) {
  cap_vlaanderen_jaar <- "niet lineair"
} else {
  cap_vlaanderen_jaar <- "mogelijk niet lineair"
}
```

```{r {{id}}-vlaanderen-jaar, fig.cap = paste0("Vlaamse indices voor ", soort_naam, " op basis van jaarlijkse data. De trend is ", cap_vlaanderen_jaar, "."), fig.height = 50 / 25.4}
ggplot(
  index_vlaanderen_jaar, 
  aes(x = jaar, y = index, ymin = lcl, ymax = ucl, group = analysis)
) +
  geom_hline(yintercept = 1, linetype = 3) +
  geom_ribbon(aes(fill = non_linear), alpha = 0.1) +
  geom_line(aes(colour = non_linear)) +
  geom_blank(
    data = data.frame(
      jaar = index_vlaanderen_jaar$jaar[1],
      index = grenzen,
      lcl = grenzen,
      ucl = grenzen,
      analysis = 1
    )
  ) +
  scale_y_continuous(labels = percent) +
  scale_fill_discrete(
    "Model", 
    breaks = c(FALSE, TRUE), 
    labels = c("log lineair", "niet lineair")
  ) +
  scale_colour_discrete(
    "Model", 
    breaks = c(FALSE, TRUE), 
    labels = c("log lineair", "niet lineair")
  ) +
  theme(
    axis.title.x = element_blank()
  )
```

```{r {{id}}-vlaanderen-cyclus-data}
deze_index %>%
  filter(cycle, parameter != "Trend") %>%
  transmute(
    cyclus = factor(parameter),
    index = median, lcl, ucl,
    non_linear, waic, analysis, status
  ) -> index_vlaanderen_cyclus
index_vlaanderen_cyclus %>%
  group_by(non_linear) %>%
  summarise(referentie = mean(index)) %>%
  inner_join(index_vlaanderen_cyclus, by = "non_linear") %>%
  mutate(
    index = exp(index - referentie),
    lcl = exp(lcl - referentie),
    ucl = exp(ucl - referentie)
  ) %>%
  select(-referentie) -> index_vlaanderen_cyclus
index_vlaanderen_cyclus %>%
  distinct(non_linear, waic) -> waic_cyclus
waic_cyclus %>%
  arrange(waic) %>%
  summarise(
    type = non_linear[1],
    delta = diff(waic)
  ) -> waic_cyclus
if (waic_cyclus$type) {
  if (waic_cyclus$delta > 5) {
    cap_vlaanderen_cyclus <- "niet lineair"
  } else {
    cap_vlaanderen_cyclus <- "mogelijk niet lineair"
  }
} else {
  cap_vlaanderen_cyclus <- "log lineair"
}
```

```{r {{id}}-vlaanderen-cyclus, fig.cap = paste0("Vlaamse indices voor ", soort_naam, " op basis van data geaggregeerd per driejaarlijkse cyclus. De trend is ", cap_vlaanderen_cyclus, "."), fig.height = 50 / 25.4}
ggplot(
  index_vlaanderen_cyclus, 
  aes(x = cyclus, y = index, ymin = lcl, ymax = ucl, group = analysis)
) +
  geom_hline(yintercept = 1, linetype = 3) +
  geom_ribbon(aes(fill = non_linear), alpha = 0.1) +
  geom_line(aes(colour = non_linear)) +
  geom_blank(
    data = data.frame(
      cyclus = index_vlaanderen_cyclus$cyclus[1],
      index = grenzen,
      lcl = grenzen,
      ucl = grenzen,
      analysis = 1
    )
  ) +
  scale_y_continuous(labels = percent) +
  scale_fill_discrete(
    "Model", 
    breaks = c(FALSE, TRUE), 
    labels = c("log lineair", "niet lineair")
  ) +
  scale_colour_discrete(
    "Model", 
    breaks = c(FALSE, TRUE), 
    labels = c("log lineair", "niet lineair")
  ) +
  theme(
    axis.title.x = element_blank()
  )
```


```{r {{id}}-design, fig.cap = paste("Aantal onderzochte relevante hokken per jaar voor", soort_naam)}
deze_index %>%
  distinct(analysis) %>%
  semi_join(x = design, by = "analysis") %>%
  filter(!is.na(jaar)) -> dit_design
if (nrow(dit_design)) {
  ggplot(dit_design, aes(x = jaar, y = hokken, colour = stratum)) +
  geom_line() +
  ylim(c(0, NA)) +
  scale_colour_discrete(drop = FALSE) +
  theme(
    axis.title.x = element_blank()
  )
}
```

```{r {{id}}-fingerprint, results = "asis"}
deze_index %>%
  distinct(analysis, status, cycle, non_linear) %>%
  arrange(cycle, non_linear) %>%
  transmute(
    model = paste(
      ifelse(cycle, "driejaarlijks", "jaarlijks"),
      ifelse(non_linear, "niet-lineair", "log-lineair")
    ),
    analyse = gsub("^([[:xdigit:]]{20})", "\\1 ", analysis),
    status = gsub("^([[:xdigit:]]{20})", "\\1 ", status)
  ) %>%
  pander(
    caption = paste0("Controlesommen van de modellen voor ", soort_naam, ".")
  )
```

\pagebreak[4]
