---
title: "Trends op basis van de Algemene Broedvogelmonitoring Vlaanderen (ABV)"
author: 
  - 
    name: "Thierry Onkelinx"
    email: "thierry.onkelinx@inbo.be"
  - 
    name: "Glenn Vermeersch"
    email: "glenn.vermeersch@inbo.be"
reportnr: "Hier komt de DOI van het rapport"
link-citations: TRUE
site: bookdown::bookdown_site
output:
  bookdown::pdf_book:
    base_format: INBOmd::inbo_rapport
  bookdown::gitbook:
    split_by: "section+number"
    template: !expr INBOmd::inbo_rapport_css("html")
  bookdown::epub_book:
    stylesheet: "css/inbo_rapport.css"
    template: !expr INBOmd::inbo_rapport_css("epub")
params:
  username: !r Sys.getenv("N2KRESULT_USERNAME")
  password: !r Sys.getenv("N2KRESULT_PASSWORD")
---

```{r results ='hide', echo = FALSE, message = FALSE, cache = FALSE, purl = FALSE}
library(knitr)
opts_chunk$set(
  echo = FALSE, 
  eval = TRUE,
  cache = FALSE,
  dpi = 300,
  fig.width = 150 / 25.4,
  fig.height = 100 / 25.4,
  warning = FALSE,
  error = FALSE,
  message = FALSE
)
library(n2khelper)
library(tidyverse)
library(scales)
library(INBOtheme)
if (opts_knit$get("rmarkdown.pandoc.to") == "html") {
  theme_set(
    theme_inbo(
      base_family = "Flanders Art Sans",
      base_size = 12
    )
  )
} else {
  opts_chunk$set(dev = "cairo_pdf")
  theme_set(
    theme_inbo(
      base_family = "Flanders Art Sans",
      base_size = 8
    )
  )
}
grenzen <- c(0.65, 1.5)
```

```{r import-results, eval = !file.exists("results.Rdata"), results = "hide"}
conn <- connect_result(username = params$username, password = params$password)
tbl(conn, "scheme") %>%
  filter(description == "Algemene broedvogels") %>%
  semi_join(
    x = tbl(conn, "species_group"),
    by = c("scheme" = "id")
  ) %>%
  select(fingerprint, species_group = description) %>%
  collect() -> species_group
aws <- aws.s3::get_bucket("n2kmonitoring", "abv/manifest", max = Inf)
map_chr(aws, "Key") %>%
  basename() %>%
  map(n2kanalysis::read_manifest, base = aws, project = "abv") -> manifests
tibble(
  timestamp = map_chr(aws, "LastModified") %>%
    gsub(pattern = "T", replacement = " ") %>%
    as.POSIXct(),
  manifest = map_chr(manifests, slot, "Fingerprint"),
  tmp = map(manifests, slot, "Manifest")
) %>%
  unnest() %>%
  arrange(desc(timestamp)) %>%
  group_by(Fingerprint) %>%
  slice(1) %>%
  select(analysis = Fingerprint, timestamp) -> recent
raw_results <- aws.s3::s3readRDS(
    "abv/results/results.rds", 
    bucket = "n2kmonitoring"
  )
map_dfr(raw_results, "result") %>%
  filter(stratum == "Vlaanderen") %>%
  select(-stratum) %>%
  inner_join(recent, by = "analysis") %>%
  inner_join(x = species_group, by = c("fingerprint" = "species_group")) -> 
  parameters
parameters %>%
  distinct(fingerprint, model_type, analysis, timestamp) %>%
  arrange(desc(timestamp)) %>%
  group_by(fingerprint, model_type) %>%
  slice(1) %>%
  semi_join(x = parameters, by = "analysis") %>%
  select(-timestamp) -> parameters
parameters %>%
  filter(grepl("composite.*non linear", model_type)) %>%
  mutate(
    cycle = grepl("cycle", model_type),
    mean = exp(mean),
    lcl = exp(lcl),
    ucl = exp(ucl)
  ) %>%
  select(-median, -model_type, -waic) -> composite
parameters %>%
  filter(grepl("^inla ", model_type)) %>%
  mutate(
    cycle = grepl("Cycle", model_type),
    non_linear = grepl("RW1", model_type)
  ) %>%
  select(-model_type) -> species
species %>%
  distinct(analysis) %>%
  mutate(
    design = map(raw_results[analysis], "design") %>%
      map("time_obs")
  ) %>%
  unnest() -> design
design %>%
  distinct(stratum) %>%
  pull(stratum) -> strata
tbl(conn, "location") %>%
  filter(fingerprint %in% strata) %>%
  select(fingerprint, stratum = description) %>%
  collect() %>%
  mutate(stratum = factor(stratum)) -> straita_description
strata_description %>%
  inner_join(design, by = c("fingerprint" = "stratum")) %>%
  transmute(analysis, stratum, jaar = cyear + 2006, hokken = n_location) ->
  design
git2rdata::read_vc(
  "location/location", 
  root = git2r::repository("~/n2k/abv")
) %>%
  inner_join(strata_description, by = c("parent" = "fingerprint")) %>%
  inner_join(
    git2rdata::read_vc(
      "observation/visit", 
      root = git2r::repository("~/n2k/abv")
    ),
    by = "location"
  ) %>%
  transmute(
    stratum,
    location = factor(location),
    sublocation = factor(sublocation),
    year, period
  ) -> visits
save(visits, design, composite, species, file = "results.Rdata")
rm(
  manifests, aws, raw_results, recent, species_group, strata_description, conn,
  strata, parameters
)
junk <- gc()
```

```{r load-data}
load("results.Rdata")
```

# Samengestelde indices

```{r samengesteld, results='asis', cache = FALSE}
composite %>%
  distinct(fingerprint, species_group) %>%
  arrange(species_group) %>%
  pull(fingerprint) %>%
  sapply(
    function(id) {
      knit_expand("_samengesteld.Rmd", id = id)
    }
  ) %>%
  paste(collapse = "\n\n") -> rmd
knit(text = rmd, quiet = TRUE) %>%
  cat()
```

